### ISSUE TITLE
Feature request: Preserve new lines while saving text

### ISSUE THREAD

**Issue by kirtan403** [chrschorn/oneclick-send-to-trello#1]
When saving the connection to trello I would love to preserve the new lines saved in description. Currently all the text is getting saved as a single paragraph.

**Comment by kirtan403** [comment]
I see it is completed and deployed and live on chrome web store. I appreciate the work done by you. Great!

**Comment by chrschorn** [comment]
Oh, I didn't even see it here, I only saw the Chrome web store suggestion. No worries, if I have the time and the feature is not too big I'll try to add it!
