### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by cptvincer** [chrschorn/oneclick-send-to-trello#6]
Installed on Microsoft Edge(chromium), latest.
Aproved the aplication in trello, but nothing happens. When clicking login and aproving on the new tab asking for aproval the page only refreshs, instead of showing that it was aproved.

In trello itself, in settings, the extension is there as approved...

but the extension doesnt recognize its approved. It only ever shows 'login' and activating it in any way (context menu or icon) brings up the page asking for login.

**Comment by adelendagit** [comment]
Yep, I am seeing the same behaviour in Chrome

**Comment by chrschorn** [comment]
I've been looking into it. New users indeed weren't able to login, but it was hard to diagnose. Fixing this also required almost a whole rewrite because I needed to upgrade to manifest v3. Should be fixed once v3.0.0 goes live on the Chrome Web Store!

**Comment by chrschorn** [comment]
v3.0.0 is live now, let me know if there are any other issues!
